### ISSUE TITLE
code incomplete

### ISSUE THREAD

**Issue by rishabhjoshi** [kiransd1008/WackySquirrel#2]
#### Line 358 code is incomplete.

code snippet - 

```
while(1){
if(some_condition)
break;
}
```

**Comment by kiransd1008** [comment]
the function angle_rotate is being used by right_degrees and left_degrees where angle_rotate is looped till shaftcount becomes equal to required ShaftCount....while loop in angle_rotate is neccessary to keep it executimg until required shaft count run repeatedly till required shaftcount/rotation...ok?

**Comment by rishabhjoshi** [comment]
So you mean to say that the "condition" is volatile right? And the it will take data from memory everytime it executes the statement?

**Comment by kiransd1008** [comment]
Exactly.. The variables ShaftCountRight, shaftcountleft and pulse variables are volatile since configuration of their pins/ports...
